name: Discord Notification

on:
  issues:
    types: [assigned]
  workflow_run:
    
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Hey! A pull request has been assigned to you."

