on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create Branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          git checkout -b issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}
          git push --set-upstream origin issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}

      - name: Update Issue
        run: |
          branch_name=issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}
          issue_number=${{ github.event.issue.number }}
          curl \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${issue_number} \
          -d "{\"head\":\"${{ github.ref }}\",\"labels\":[\"branch\"],\"body\":\"Branch created: $branch_name\"}"
