on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Create Branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          issue_numer="${{ github.event.issue.number}}
          branch_name="${{ github.event.issue.number }}-${{ github.event.issue.title }}"
          branch_name=${branch_name// /-}
          branch_name=${branch_name//[^a-zA-Z0-9_-]/}
          gh issue develop $issue_number --name "$branch_name" --base main

