name: Create Branch on Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Branch
        run: |
          sudo git config --global user.email "action@github.com"
          sudo git config --global user.name "Github Actions"
          sudo git checkout -b issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}
          sudo git push --set-upstream origin issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}
