on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Create Branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          branch_name="${{ github.event.issue.number }}-${{ github.event.issue.title }}"
          branch_name=${branch_name// /-}
          branch_name=${branch_name//[^a-zA-Z0-9_-]/}
          git checkout -b "$branch_name"
          git push --set-upstream origin "$branch_name"

      - name: Link Branch to Issue
        run: |
          branch_name=issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}
          issue_number=${{ github.event.issue.number }}
          branch_ref=$(git rev-parse --short HEAD)
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${issue_number} \
            -d "{\"head\":\"${branch_ref}\",\"body\":\"Branch created: ${branch_name}\"}"
